[tool.poetry]
name = "els"
version = "0.1.0"
description = ""
authors = ["tanluuuuuuu <ngovantanluu@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
elasticsearch = "^8.16.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
